### ISSUE TITLE
UBsync not in OpenStore, manual install doesn't work

### ISSUE THREAD

**Issue by DuncanCragg** [belohoub/UBsync#29]
Probably not an issue with UBsync, sorry...

I'm on a OnePlus 5T and last time I installed UT a couple of days ago UBsync was there and worked great.

I then went back to stock on this 5T, and installed UT on another 5T...

..but UBsync isn't in the onboard OpenStore app any more!

So I got UBsync from the OpenStore web page and installed it and it runs apparently OK, but the sync won't start (and I can't uninstall it either).

Again, apologies if this is nothing to do with you, but if you can help me that would be fab!

**Comment by belohoub** [comment]
Hello @DuncanCragg ,
that's because we're currently in the testing phase for Focal and there is not final release for Focal yet. 

You don't see UBsync in the OpenStore, because there is no UBsync for your OS version yet. You can download UBsync for Xenial from the OpenStore web page, but if you install it on Focal, it will not work, as it depends on some deprecated (Xenial-only) features.

But here is [0.8.0-RC1](https://github.com/belohoub/UBsync/releases) pre-release for testing the Focal port.

According to the current feedback, it works well, and if there will be no severe issue within few days, I'll make the final release for the OpenStore as well. You can wait for the final release, or you can try install the pre-release manually now and report issues if any ;-)

**Comment by DuncanCragg** [comment]
Ah - I worked this out for myself and then downgraded to Xenial!!! Now I need to upgrade again to try 0.8.0 out! argh.

**Comment by belohoub** [comment]
On Xenial, you can still use v0.7.5.

**Comment by belohoub** [comment]
No issues created for a long time, thus 0.8.0-RC1 becomes [0.8.0](https://github.com/belohoub/UBsync/releases/tag/0.8.0-RC1)
